name: 2024-remix_deploy

on:
  push:
    paths:
      - "views/2024-remix/**"
      - ".github/workflows/2024-remix_deploy.yaml"
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        working-directory: views/2024-remix

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          # directory: build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
          workingDirectory: views/2024-remix
          branch: main
          command: pages deploy ./build/client --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}

      - name: print deployment-url
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
