name: hono_deploy

on:
  push:
    paths:
      - 'server/hono/**'
      - '.github/workflows/hono_deploy.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_HONO }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.57.2"
          workingDirectory: server/hono
          packageManager: bun
          secrets: |
            GITHUB_OWNER
            GITHUB_REPO
            GITHUB_TOKEN
            API_TOKEN
        env:
          GITHUB_OWNER: ${{ secrets.OWNER }}
          GITHUB_REPO: ${{ secrets.REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
