name: remix-2024_deploy

on:
  push:
    paths:
      - 'views/remix-2024/**'
      - '.github/workflows/remix-2024_deploy.yaml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: views/remix-2024
      
      - name: Build
        run: bunx --bun remix vite:build      
        working-directory: views/remix-2024

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with: 
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
